"""Feature matrix analysis: Markdown report of features and profile usage."""

from __future__ import annotations

import json
from pathlib import Path

from solen.core.feature import expand_feature_dependencies
from solen.core.profile import parse_profile


def collect_profile_features(repo_root: Path) -> dict[str, tuple[list[str], set[str]]]:
    """Map profile name -> (literal features, expanded feature set).

    Uses generated/profiles when present, otherwise falls back to profiles/.
    """
    profiles: dict[str, tuple[list[str], set[str]]] = {}
    features_dir = repo_root / "features"

    for base in (repo_root / "generated" / "profiles", repo_root / "profiles"):
        if not base.is_dir():
            continue
        files = sorted(
            p for p in base.iterdir()
            if p.is_file() and not p.name.startswith(".") and p.name != "README.md"
        )
        if not files:
            continue
        for profile_path in files:
            try:
                data = parse_profile(profile_path, base)
            except Exception:
                continue
            try:
                expanded = set(expand_feature_dependencies(features_dir, data.features))
            except Exception:
                expanded = set(data.features)
            profiles[profile_path.stem] = (data.features, expanded)
        break

    return profiles


def analyze_features(repo_root: Path, output_path: Path) -> int:
    """Write a Markdown matrix of all features and their profile usage.

    Returns the number of features analyzed.
    """
    features_dir = repo_root / "features"
    profiles = collect_profile_features(repo_root)

    rows: list[dict[str, object]] = []
    for feature_dir in sorted(features_dir.iterdir()):
        feature_json = feature_dir / "feature.json"
        is_feature = (
            feature_dir.is_dir()
            and not feature_dir.name.startswith("_")
            and feature_json.exists()
        )
        if not is_feature:
            continue
        try:
            data = json.loads(feature_json.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue

        feature_id = data.get("id", feature_dir.name)
        literal_users = sorted(
            name for name, (features, _expanded) in profiles.items() if feature_id in features
        )
        expanded_users = sorted(
            name for name, (_features, expanded) in profiles.items() if feature_id in expanded
        )
        used_by = sorted(set(literal_users) | set(expanded_users))

        rows.append({
            "id": feature_id,
            "name": data.get("name", feature_dir.name),
            "version": data.get("version", ""),
            "depends_on": data.get("dependsOn", []),
            "provides": data.get("provides", []),
            "post_install_check": bool(data.get("postInstallCheck")),
            "used_by": used_by,
            "is_bundle": feature_id.startswith("bundle-"),
        })

    lines = [
        "# Solen Feature Matrix",
        "",
        f"Generated by `solen analyze features` — "
        f"{len(rows)} features, {len(profiles)} profile(s).",
        "",
        "| Feature | Name | Version | Dependencies | Provides | Used by |",
        "|---|---|---|---|---|---|",
    ]

    for row in rows:
        feature_id = str(row["id"])
        label = f"`{feature_id}` (bundle)" if row["is_bundle"] else f"`{feature_id}`"
        deps = ", ".join(str(d) for d in row["depends_on"]) if row["depends_on"] else "—"
        provides = ", ".join(str(p) for p in row["provides"]) if row["provides"] else "—"
        users = ", ".join(str(u) for u in row["used_by"]) if row["used_by"] else "—"
        lines.append(
            f"| {label} | {row['name']} | {row['version']} | {deps} | {provides} | {users} |"
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rows)
