version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # traefik dashboard (insecure)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  codeserver:
    image: ghcr.io/ebpro/solen:feature-minimal-codeserver
    user: "1001:1001"
    volumes:
      - ./:/workspace:rw
    working_dir: /workspace
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codeserver.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.codeserver.entrypoints=websecure"
      - "traefik.http.routers.codeserver.tls=true"
      - "traefik.http.routers.codeserver.tls.certresolver=le"
      - "traefik.http.services.codeserver.loadbalancer.server.port=8080"
    restart: unless-stopped
