sonar.projectKey=com.ebpro:jupyter-base
sonar.projectName=jupyter-base
sonar.sourceEncoding=UTF-8
sonar.sources=solen-cli,scripts,features
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualityGate.wait=true
sonar.qualityGate.timeout=300
sonar.exclusions=generated/**,artefacts/**,devcontainer/**,**/dist/**
