sonar.projectKey=com.ebpro:solen
sonar.projectName=solen
sonar.sourceEncoding=UTF-8
sonar.sources=solen-cli,scripts,features
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=generated/**,artefacts/**,devcontainer/**,**/dist/**
