#!/bin/bash

for script in $(ls -d /usr/local/bin/before-notebook.d/*); do 
    echo "running $script before start (binder ?)"
    bash $script
done

#Do the normal Binder start thing here...
# if in binder 
if [ $0 eq "start" ]
then
    exec "$@"
else
    echo "Not in Binder."
fi