#!/usr/bin/env bash
set -euo pipefail

# fetch-artefacts.sh
# Download and extract offloaded artefacts into ./artefacts for local builds or CI.
# Supports either a direct URL (ENV ARTEFACT_URL or --url) or a manifest produced by
# `scripts/offload-artefacts.sh` together with a base URL via ENV ARTEFACTS_BASE_URL.

usage() {
  cat <<EOF
Usage: $0 [--url URL] [--manifest PATH] [--dest DIR] [--no-verify]

Environment:
  ARTEFACT_URL         direct URL to tarball (overrides manifest)
  ARTEFACTS_BASE_URL   base URL where tarball and .sha256 live (used with manifest)
  ARTEFACT_SHA256      expected sha256 checksum (optional)

Examples:
  # direct URL
  ARTEFACT_URL=https://.../toolcache-20251208T....tar.gz ./scripts/fetch-artefacts.sh

  # using manifest generated by offload script and a base URL
  ARTEFACTS_BASE_URL=https://github.com/ebpro/jupyter-base/releases/download/v0.0.0 \
    ./scripts/fetch-artefacts.sh --manifest artefacts/offload/toolcache-manifest-20251208T....json

EOF
}

MANIFEST=""
URL=""
DEST="${PWD}/artefacts"
VERIFY=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help) usage; exit 0 ;;
    --manifest) MANIFEST="$2"; shift 2 ;;
    --url) URL="$2"; shift 2 ;;
    --dest) DEST="$2"; shift 2 ;;
    --no-verify) VERIFY=false; shift ;;
    *) echo "Unknown arg: $1"; usage; exit 1 ;;
  esac
done

set -u

echo "Destination: $DEST"
mkdir -p "$DEST"

# Resolve URL from args/env/manifest
if [[ -n "${ARTEFACT_URL:-}" ]]; then
  URL="${ARTEFACT_URL:-}"
fi
if [[ -n "$URL" ]]; then
  echo "Using artefact URL: $URL"
fi

if [[ -z "$URL" && -n "$MANIFEST" ]]; then
  if [[ ! -f "$MANIFEST" ]]; then
    echo "Manifest file not found: $MANIFEST" >&2
    exit 1
  fi
  TARFILE=$(jq -r '.tarball // empty' "$MANIFEST") || TARFILE=""
  SHAFILE=$(jq -r '.sha256_file // empty' "$MANIFEST") || SHAFILE=""
  if [[ -z "$TARFILE" ]]; then
    echo "Manifest does not contain 'tarball' field: $MANIFEST" >&2
    exit 1
  fi
  if [[ -z "${ARTEFACTS_BASE_URL:-}" ]]; then
    echo "ARTEFACTS_BASE_URL not set; can't resolve remote tarball from manifest." >&2
    exit 1
  fi
  # strip possible trailing slash from base URL
  BASE=${ARTEFACTS_BASE_URL%/}
  URL="$BASE/$TARFILE"
  if [[ -n "$SHAFILE" ]]; then
    SHA_URL="$BASE/$SHAFILE"
  else
    SHA_URL="$BASE/$TARFILE.sha256"
  fi
  echo "Resolved tarball URL: $URL"
  echo "Resolved sha URL: $SHA_URL"
fi

if [[ -z "$URL" ]]; then
  echo "No artefact URL provided. Either set ARTEFACT_URL, pass --url, or provide --manifest with ARTEFACTS_BASE_URL." >&2
  exit 1
fi

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

ARCHIVE="$TMPDIR/$(basename "$URL")"

echo "Downloading $URL to $ARCHIVE"
if command -v curl >/dev/null 2>&1; then
  curl -fsSL -o "$ARCHIVE" "$URL"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$ARCHIVE" "$URL"
else
  echo "Neither curl nor wget available" >&2
  exit 1
fi

EXPECTED=""
if [[ -n "${ARTEFACT_SHA256:-}" ]]; then
  EXPECTED="$ARTEFACT_SHA256"
fi

if [[ -z "$EXPECTED" && -n "${SHA_URL:-}" && "$VERIFY" = true ]]; then
  echo "Attempting to download checksum from $SHA_URL"
  SHA_LOCAL="$TMPDIR/$(basename "$SHA_URL")"
  if command -v curl >/dev/null 2>&1; then
    if ! curl -fsSL -o "$SHA_LOCAL" "$SHA_URL"; then
      echo "Warning: could not download checksum from $SHA_URL" >&2
    else
      # extract first token that looks like a hex checksum
      EXPECTED=$(awk '{print $1}' "$SHA_LOCAL" | head -n1 | tr -d '\r\n') || true
    fi
  fi
fi

if [[ "$VERIFY" = true && -n "$EXPECTED" ]]; then
  echo "Verifying checksum..."
  if command -v sha256sum >/dev/null 2>&1; then
    CALC=$(sha256sum "$ARCHIVE" | awk '{print $1}')
  elif command -v shasum >/dev/null 2>&1; then
    CALC=$(shasum -a 256 "$ARCHIVE" | awk '{print $1}')
  else
    echo "No checksum tool available (sha256sum or shasum)" >&2
    exit 1
  fi
  if [[ "$CALC" != "$EXPECTED" ]]; then
    echo "Checksum mismatch! expected=$EXPECTED got=$CALC" >&2
    exit 1
  fi
  echo "Checksum OK"
elif [[ "$VERIFY" = true ]]; then
  echo "Warning: no expected checksum available; skipping verification" >&2
fi

echo "Extracting archive into $DEST"
tar -xzf "$ARCHIVE" -C "$DEST"

echo "Extraction complete. Contents under $DEST:"
ls -la "$DEST" | sed -n '1,120p'

echo "fetch-artefacts.sh finished successfully"
