channels:
- conda-forge
- nodefaults
- terradue

dependencies:
- black
- isort
- jupyter-book
- jupyter-server-proxy
- jupyterhub
- jupyterlab >=4.0.0
# - jupyterlab_rise  # jlab < 4.0
- jupyterlab_widgets
# - jupyterlab-drawio  # jlab < 4.0
- jupyterlab-git
# - jupyterlab-link-share # jlab < 4.0
# - jupyterlab-myst  # jlab < 4.0
# - jupyterlab-system-monitor # jlab < 4.0
# - jupyterlab-tour
- jupytext
# - mamba_gator
- nb_conda_kernels
- nbgitpuller
- pandas
- websockify

##- sphinx-inline-tabs


# - jupyterlab>=3.0.0,<4.0.0a0 # for lsp # jlab < 4.0
#- jupyterlab-lsp # jlab < 4.0
#- python-language-server # jlab < 4.0
#- jupyterlab-spellchecker # jlab < 4.0
# - jedi-language-server
- seaborn

- jupyterlab_code_formatter
- sphinxcontrib-plantuml