channels:
- conda-forge
- nodefaults

dependencies:
- black
- isort
- jupyter-book
- jupyter-server-proxy
- jupyterhub
- jupyterlab>=3.0.0,<4.0.0a0 # for lsp
- jupyterlab_rise
- jupyterlab_widgets
- jupyterlab-drawio
- jupyterlab-git
- jupyterlab-link-share
- jupyterlab-myst
- jupyterlab-system-monitor
# - jupyterlab-tour
- jupytext
# - mamba_gator
- nb_conda_kernels
- nbgitpuller
- pandas
- sphinx-inline-tabs
- websockify
- jupyterlab-spellchecker

- jupyterlab-lsp
- python-language-server
